### ISSUE TITLE
Keybinding with no `args` throws 

### ISSUE THREAD

**Issue by kaste** [gladclef/HoverDocs#3]
E.g.

```
  { "keys": ["ctrl+q"], "command": "hover_docs"},
```

throws.  The intention here is that I don't override the "display_style" but use the globally configured one. 

BTW

```
  { "keys": ["ctrl+q"], "command": "hover_docs", "args": {}},
```

works as expected.

**Comment by gladclef** [comment]
Once I address the other two issues I'll push a new tag, which should let you update via package control. Until then, you can clone this repo to preview the change. Thanks for the feedback!!!
