### ISSUE TITLE
None exception on untitled views/buffers

### ISSUE THREAD

**Issue by kaste** [gladclef/HoverDocs#5]
![image](https://user-images.githubusercontent.com/8558/183226111-c2d1f598-031a-4e2d-b696-af3eff24822d.png)

```
  File "...\Installed Packages\HoverDocs.sublime-package\HoverDocs.py", line 56, in find_symbol_definition
    a, ext = os.path.splitext(fn)
  File "./python3.8/ntpath.py", line 204, in splitext
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

apparently `fn` is None here for unsaved views/buffers.

**Comment by gladclef** [comment]
Once I address the other two issues I'll push a new tag, which should let you update via package control. Until then, you can clone this repo to preview the change. Thanks for the feedback!!!
